// Base UI exposes presence attributes, not Ark/Radix data-state values.
export const conditions = {
  ...Object.fromEntries(
    [
      'amber',
      'blue',
      'bronze',
      'brown',
      'crimson',
      'cyan',
      'gold',
      'grass',
      'green',
      'indigo',
      'iris',
      'jade',
      'lime',
      'mauve',
      'mint',
      'neutral',
      'olive',
      'orange',
      'pink',
      'plum',
      'purple',
      'red',
      'ruby',
      'sage',
      'sand',
      'sky',
      'slate',
      'teal',
      'tomato',
      'violet',
      'yellow',
    ].flatMap((name) => [
      [`accent_${name}`, `[data-accent=${name}] &`],
      [`gray_${name}`, `[data-gray=${name}] &`],
    ]),
  ),
  dark: '[data-theme=dark] &',
  checked: '&:is([data-checked], [aria-checked=true])',
  unchecked: '&[data-unchecked]',
  highlighted: '&[data-highlighted]',
  selected: '&:is([data-selected], [aria-selected=true])',
  open: '&[data-open]',
  closed: '&[data-closed]',
  expanded: '&[data-panel-open]',
  startingStyle: '&[data-starting-style]',
  endingStyle: '&[data-ending-style]',
  invalid: '&:is([data-invalid], [aria-invalid=true])',
  indeterminate: '&[data-indeterminate]',
} as const
