import { defineSlotRecipe } from '@pandacss/dev'
import { control, popup, item, focusRing } from '../shared'

export const combobox = defineSlotRecipe({
  className: 'kiso-combobox',
  slots: [
    'label',
    'inputGroup',
    'input',
    'trigger',
    'clear',
    'positioner',
    'popup',
    'list',
    'item',
    'itemIndicator',
    'groupLabel',
    'empty',
    'chips',
    'chip',
    'chipRemove',
    'separator',
  ],
  staticCss: ['*', { size: ['*'], responsive: true }],
  base: {
    label: { fontSize: 'sm', fontWeight: 'medium', display: 'block', mb: '2' },
    inputGroup: {
      ...control,
      display: 'flex',
      alignItems: 'center',
      width: 'full',
      border: '1px solid',
      borderColor: 'border.strong',
      bg: 'surface',
      px: '3',
      gap: '1',
      _focusWithin: {
        borderColor: 'accent',
        outline: '2px solid',
        outlineColor: 'accent.subtle',
        outlineOffset: '1px',
      },
      _invalid: { borderColor: 'danger' },
    },
    input: {
      width: 'full',
      minWidth: 0,
      flex: 1,
      bg: 'transparent',
      outline: 'none',
      _placeholder: { color: 'fg.subtle' },
      _disabled: { opacity: 0.5 },
    },
    trigger: {
      ...focusRing,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: 'fg.muted',
      borderRadius: '4px',
      w: '6',
      h: '6',
      '& svg': { w: '3.5', h: '3.5' },
    },
    clear: {
      ...focusRing,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: 'fg.muted',
      borderRadius: '4px',
      w: '6',
      h: '6',
      '& svg': { w: '3', h: '3' },
    },
    positioner: { zIndex: 50 },
    popup: { ...popup, minWidth: 'var(--anchor-width)', maxWidth: 'calc(100vw - 24px)' },
    list: { maxHeight: 'min(300px, var(--available-height))', overflowY: 'auto', outline: 'none' },
    item,
    itemIndicator: { ml: 'auto', '& svg': { w: '3.5', h: '3.5' } },
    groupLabel: { px: '3', py: '2', fontSize: 'xs', color: 'fg.subtle' },
    empty: { fontSize: 'sm', color: 'fg.muted', textAlign: 'center', '&:not(:empty)': { p: '5' } },
    chips: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: '1.5',
      minWidth: 0,
      py: '1',
    },
    chip: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '1',
      fontSize: 'xs',
      bg: 'accent.subtle',
      color: 'accent.fg',
      px: '2',
      py: '1',
      borderRadius: 'control',
    },
    chipRemove: { ...focusRing, borderRadius: '2px', color: 'accent.fg', display: 'flex' },
    separator: { h: '1px', bg: 'border', my: '1' },
  },
  variants: {
    size: {
      sm: { inputGroup: { minH: '8', fontSize: 'xs' } },
      md: { inputGroup: { minH: '9', fontSize: 'sm' } },
      lg: { inputGroup: { minH: '11', fontSize: 'md' } },
    },
  },
  defaultVariants: { size: 'md' },
})
