import { defineSlotRecipe } from '@pandacss/dev'
import { arrow, fieldGroupVariants, groupLabel, item, popup, popupBackdrop } from '../shared'

const iconButton = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  flexShrink: '0',
  color: 'fg.subtle',
  borderRadius: 'l1',
  cursor: 'pointer',
  focusVisibleRing: 'outside',
  _hover: { color: 'fg.default', bg: 'gray.plain.bg.hover' },
} as const

// Shared by Combobox and Autocomplete.
export const combobox = defineSlotRecipe({
  className: 'kiso-combobox',
  jsx: ['Combobox', /^Combobox\./, 'Autocomplete', /^Autocomplete\./],
  slots: [
    'label',
    'inputGroup',
    'input',
    'trigger',
    'clear',
    'icon',
    'positioner',
    'popup',
    'list',
    'item',
    'itemIndicator',
    'groupLabel',
    'empty',
    'chips',
    'chip',
    'chipRemove',
    'separator',
    'row',
    'backdrop',
    'arrow',
  ],
  base: {
    label: { display: 'block', textStyle: 'label', mb: '1.5' },
    inputGroup: {
      display: 'flex',
      alignItems: 'center',
      width: 'full',
      borderRadius: 'l2',
      color: 'fg.default',
      transitionProperty: 'background-color, border-color',
      transitionDuration: 'fast',
      _disabled: { layerStyle: 'disabled' },
    },
    input: {
      flex: '1',
      minWidth: '0',
      alignSelf: 'stretch',
      bg: 'transparent',
      outline: '0',
    },
    trigger: iconButton,
    clear: iconButton,
    // A static chevron for inputs without a Trigger button.
    icon: { display: 'flex', flexShrink: '0', color: 'fg.subtle' },
    positioner: { zIndex: 'popover' },
    popup: {
      ...popup,
      display: 'flex',
      flexDirection: 'column',
      minWidth: 'var(--anchor-width)',
      maxWidth: 'var(--available-width)',
    },
    list: {
      display: 'flex',
      flexDirection: 'column',
      maxHeight: 'min(var(--available-height), {sizes.80})',
      overflowY: 'auto',
      outline: '0',
      '&:empty': { display: 'none' },
    },
    item: { ...item, justifyContent: 'space-between', cursor: 'pointer' },
    itemIndicator: { display: 'flex', color: 'colorPalette.plain.fg' },
    groupLabel,
    empty: { color: 'fg.muted', textAlign: 'center', '&:not(:empty)': { p: '4' } },
    chips: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: '1',
      flex: '1',
      minWidth: '0',
    },
    chip: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '1',
      h: '6',
      px: '2',
      textStyle: 'xs',
      fontWeight: 'medium',
      borderRadius: 'l1',
      bg: 'colorPalette.subtle.bg',
      color: 'colorPalette.subtle.fg',
      _highlighted: { bg: 'colorPalette.subtle.bg.hover' },
    },
    chipRemove: {
      display: 'flex',
      borderRadius: 'l1',
      cursor: 'pointer',
      focusVisibleRing: 'outside',
      _icon: { boxSize: '3' },
    },
    separator: { h: '1px', bg: 'border', my: '1' },
    // Grid layouts: each Row holds several items side by side.
    row: { display: 'flex', gap: '0.5' },
    backdrop: popupBackdrop,
    arrow,
  },
  defaultVariants: { variant: 'outline', size: 'md' },
  variants: {
    variant: {
      outline: { inputGroup: fieldGroupVariants.outline },
      surface: { inputGroup: fieldGroupVariants.surface },
      subtle: { inputGroup: fieldGroupVariants.subtle },
    },
    size: {
      xs: {
        inputGroup: { minH: '8', px: '2', gap: '1', textStyle: 'sm' },
        trigger: { boxSize: '5', _icon: { boxSize: '3.5' } },
        icon: { _icon: { boxSize: '3.5' } },
        clear: { boxSize: '5', _icon: { boxSize: '3' } },
        popup: { p: '1', gap: '0.5', textStyle: 'sm' },
        item: { minH: '8', '--item-px': 'spacing.1', gap: '2', _icon: { boxSize: '3.5' } },
        groupLabel: { minH: '8', '--item-px': 'spacing.1' },
      },
      sm: {
        inputGroup: { minH: '9', px: '2.5', gap: '1', textStyle: 'sm' },
        trigger: { boxSize: '6', _icon: { boxSize: '4' } },
        icon: { _icon: { boxSize: '4' } },
        clear: { boxSize: '6', _icon: { boxSize: '3.5' } },
        popup: { p: '1', gap: '0.5', textStyle: 'sm' },
        item: { minH: '9', '--item-px': 'spacing.1.5', gap: '2', _icon: { boxSize: '4' } },
        groupLabel: { minH: '9', '--item-px': 'spacing.1.5' },
      },
      md: {
        inputGroup: { minH: '10', px: '3', gap: '1', textStyle: 'md' },
        trigger: { boxSize: '6', _icon: { boxSize: '4' } },
        icon: { _icon: { boxSize: '4' } },
        clear: { boxSize: '6', _icon: { boxSize: '3.5' } },
        popup: { p: '1', gap: '0.5', textStyle: 'md' },
        item: { minH: '10', '--item-px': 'spacing.2', gap: '2', _icon: { boxSize: '4' } },
        groupLabel: { minH: '10', '--item-px': 'spacing.2' },
      },
      lg: {
        inputGroup: { minH: '11', px: '3.5', gap: '1.5', textStyle: 'md' },
        trigger: { boxSize: '7', _icon: { boxSize: '4.5' } },
        icon: { _icon: { boxSize: '4.5' } },
        clear: { boxSize: '7', _icon: { boxSize: '4' } },
        popup: { p: '1', gap: '0.5', textStyle: 'md' },
        item: { minH: '11', '--item-px': 'spacing.2.5', gap: '2', _icon: { boxSize: '4.5' } },
        groupLabel: { minH: '11', '--item-px': 'spacing.2.5' },
      },
      xl: {
        inputGroup: { minH: '12', px: '4', gap: '1.5', textStyle: 'lg' },
        trigger: { boxSize: '8', _icon: { boxSize: '5' } },
        icon: { _icon: { boxSize: '5' } },
        clear: { boxSize: '8', _icon: { boxSize: '4.5' } },
        popup: { p: '1', gap: '1', textStyle: 'lg' },
        item: { minH: '12', '--item-px': 'spacing.3', gap: '3', _icon: { boxSize: '5' } },
        groupLabel: { minH: '12', '--item-px': 'spacing.3' },
      },
      '2xl': {
        inputGroup: { minH: '16', px: '4.5', gap: '2', textStyle: '3xl' },
        trigger: { boxSize: '10', _icon: { boxSize: '6' } },
        icon: { _icon: { boxSize: '6' } },
        clear: { boxSize: '10', _icon: { boxSize: '5' } },
        popup: { p: '1', gap: '1', textStyle: 'xl' },
        item: { minH: '14', '--item-px': 'spacing.3', gap: '3', _icon: { boxSize: '5' } },
        groupLabel: { minH: '14', '--item-px': 'spacing.3' },
      },
    },
  },
})
