import { defineSlotRecipe } from '@pandacss/dev'

// The side follows Base UI's swipeDirection prop (data-swipe-direction): down is a bottom sheet.
export const drawer = defineSlotRecipe({
  className: 'kiso-drawer',
  jsx: ['Drawer', /^Drawer\./],
  slots: [
    'backdrop',
    'viewport',
    'popup',
    'content',
    'header',
    'body',
    'footer',
    'title',
    'description',
    'close',
    'closeTrigger',
  ],
  base: {
    backdrop: {
      position: 'fixed',
      inset: '0',
      bg: 'black.a7',
      zIndex: 'overlay',
      opacity: 'calc(1 - var(--drawer-swipe-progress, 0))',
      transitionProperty: 'opacity',
      transitionDuration: 'normal',
      _startingStyle: { opacity: 0 },
      _endingStyle: { opacity: 0 },
    },
    viewport: { position: 'fixed', inset: '0', zIndex: 'modal', pointerEvents: 'none' },
    popup: {
      position: 'fixed',
      display: 'flex',
      flexDirection: 'column',
      pointerEvents: 'auto',
      bg: 'gray.surface.bg',
      color: 'fg.default',
      boxShadow: 'lg',
      outline: '0',
      textStyle: 'sm',
      transitionProperty: 'translate',
      transitionDuration: 'slow',
      transitionTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)',
      '&[data-swiping]': { transitionDuration: '0s' },
      '&[data-swipe-direction=down]': {
        insetInline: '0',
        bottom: '0',
        mx: 'auto',
        maxWidth: 'var(--drawer-size)',
        maxHeight: 'calc(100dvh - token(spacing.12))',
        borderTopRadius: 'l3',
        translate: '0 var(--drawer-swipe-movement-y, 0px)',
        _startingStyle: { translate: '0 100%' },
        _endingStyle: { translate: '0 100%' },
      },
      '&[data-swipe-direction=up]': {
        insetInline: '0',
        top: '0',
        mx: 'auto',
        maxWidth: 'var(--drawer-size)',
        maxHeight: 'calc(100dvh - token(spacing.12))',
        borderBottomRadius: 'l3',
        translate: '0 var(--drawer-swipe-movement-y, 0px)',
        _startingStyle: { translate: '0 -100%' },
        _endingStyle: { translate: '0 -100%' },
      },
      '&[data-swipe-direction=right]': {
        insetBlock: '0',
        right: '0',
        width: 'min(var(--drawer-size), 100vw)',
        translate: 'var(--drawer-swipe-movement-x, 0px) 0',
        _startingStyle: { translate: '100% 0' },
        _endingStyle: { translate: '100% 0' },
      },
      '&[data-swipe-direction=left]': {
        insetBlock: '0',
        left: '0',
        width: 'min(var(--drawer-size), 100vw)',
        translate: 'var(--drawer-swipe-movement-x, 0px) 0',
        _startingStyle: { translate: '-100% 0' },
        _endingStyle: { translate: '-100% 0' },
      },
    },
    content: {
      display: 'flex',
      flexDirection: 'column',
      gap: { base: '4', md: '6' },
      flex: '1',
      overflowY: 'auto',
      p: { base: '4', md: '6' },
      pb: 'max(token(spacing.6), env(safe-area-inset-bottom))',
    },
    header: { display: 'flex', flexDirection: 'column', gap: '1' },
    body: { display: 'flex', flexDirection: 'column', gap: '4', flex: '1' },
    footer: { display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '3' },
    title: { fontWeight: 'semibold', textStyle: 'lg', color: 'fg.default' },
    description: { color: 'fg.muted', textStyle: 'sm' },
    close: {},
    closeTrigger: { position: 'absolute', top: '3', insetInlineEnd: '3' },
  },
  defaultVariants: { size: 'md' },
  variants: {
    size: {
      xs: { popup: { '--drawer-size': 'sizes.xs' } },
      sm: { popup: { '--drawer-size': 'sizes.sm' } },
      md: { popup: { '--drawer-size': 'sizes.md' } },
      lg: { popup: { '--drawer-size': 'sizes.lg' } },
      xl: { popup: { '--drawer-size': 'sizes.xl' } },
      full: { popup: { '--drawer-size': '100vw' } },
    },
  },
})
