import { defineSlotRecipe } from '@pandacss/dev'
import { control, popup } from '../shared'
export const navigationMenu = defineSlotRecipe({
  className: 'kiso-navigation',
  slots: [
    'root',
    'list',
    'item',
    'trigger',
    'icon',
    'content',
    'positioner',
    'popup',
    'viewport',
    'link',
    'arrow',
    'backdrop',
  ],
  staticCss: ['*'],
  base: {
    root: { position: 'relative' },
    list: { display: 'flex', alignItems: 'center', gap: '1', listStyle: 'none' },
    trigger: {
      ...control,
      display: 'flex',
      alignItems: 'center',
      gap: '2',
      px: '3',
      h: '9',
      fontSize: 'sm',
      color: 'fg.muted',
      _hover: { bg: 'surface.subtle', color: 'fg' },
      _open: { bg: 'surface.subtle', color: 'fg' },
    },
    icon: {
      '& svg': { w: '3', h: '3', transition: 'transform 150ms' },
      _open: { transform: 'rotate(180deg)' },
    },
    positioner: { zIndex: 50 },
    popup: { ...popup, maxWidth: 'min(480px, calc(100vw - 24px))' },
    viewport: { position: 'relative', overflow: 'hidden' },
    content: { p: '3' },
    link: {
      ...control,
      display: 'block',
      px: '3',
      py: '2.5',
      fontSize: 'sm',
      color: 'fg',
      textDecoration: 'none',
      _hover: { bg: 'accent.subtle', color: 'accent.fg' },
      '&[data-active]': { color: 'accent.fg' },
    },
  },
})
