import { defineSlotRecipe } from '@pandacss/dev'
import { morphPopup, morphPositioner, popup } from '../shared'

export const navigationMenu = defineSlotRecipe({
  className: 'kiso-navigation',
  jsx: ['NavigationMenu', /^NavigationMenu\./],
  slots: [
    'root',
    'list',
    'item',
    'trigger',
    'icon',
    'content',
    'positioner',
    'popup',
    'viewport',
    'link',
    'arrow',
    'backdrop',
  ],
  base: {
    root: { position: 'relative' },
    list: { display: 'flex', alignItems: 'center', gap: '1', listStyle: 'none' },
    trigger: {
      display: 'flex',
      alignItems: 'center',
      gap: '1.5',
      h: '9',
      px: '3',
      borderRadius: 'l2',
      textStyle: 'sm',
      fontWeight: 'medium',
      color: 'fg.muted',
      cursor: 'pointer',
      outline: '0',
      transitionProperty: 'background-color, color',
      transitionDuration: 'fast',
      focusVisibleRing: 'outside',
      _hover: { bg: 'gray.plain.bg.hover', color: 'fg.default' },
      // Base UI marks the trigger of the open item with data-popup-open, not data-open (_open).
      '&[data-popup-open]': { bg: 'gray.plain.bg.hover', color: 'fg.default' },
    },
    icon: {
      display: 'flex',
      transitionProperty: 'rotate',
      transitionDuration: 'normal',
      _icon: { boxSize: '3.5' },
      '&[data-popup-open]': { rotate: '180deg' },
    },
    // Base UI sizes the positioner and popup for each item's content and moves them between
    // triggers; the content slides in from the side of the trigger that was left.
    positioner: { ...morphPositioner, zIndex: 'popover' },
    popup: {
      ...popup,
      ...morphPopup,
      boxShadow: 'lg',
      maxWidth: 'min(token(sizes.lg), calc(100vw - token(spacing.6)))',
    },
    viewport: { position: 'relative', overflow: 'hidden', width: 'full', height: 'full' },
    content: {
      p: '2',
      // A tall item scrolls inside the space left on screen.
      maxHeight: 'var(--available-height)',
      overflowY: 'auto',
      transitionProperty: 'opacity, translate',
      transitionDuration: 'normal, slow',
      transitionTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
      _startingStyle: { opacity: 0 },
      _endingStyle: { opacity: 0 },
      '&[data-starting-style][data-activation-direction=left]': { translate: '-50% 0' },
      '&[data-starting-style][data-activation-direction=right]': { translate: '50% 0' },
      '&[data-ending-style][data-activation-direction=left]': { translate: '50% 0' },
      '&[data-ending-style][data-activation-direction=right]': { translate: '-50% 0' },
    },
    link: {
      display: 'block',
      px: '3',
      py: '2.5',
      borderRadius: 'l2',
      textStyle: 'sm',
      color: 'fg.default',
      textDecoration: 'none',
      outline: '0',
      focusVisibleRing: 'inside',
      _hover: { bg: 'gray.surface.bg.hover' },
      '&[data-active]': { color: 'colorPalette.plain.fg' },
    },
  },
})
