import { defineSlotRecipe } from '@pandacss/dev'
import { popup } from '../shared'

export const navigationMenu = defineSlotRecipe({
  className: 'kiso-navigation',
  jsx: ['NavigationMenu', /^NavigationMenu\./],
  slots: [
    'root',
    'list',
    'item',
    'trigger',
    'icon',
    'content',
    'positioner',
    'popup',
    'viewport',
    'link',
    'arrow',
    'backdrop',
  ],
  base: {
    root: { position: 'relative' },
    list: { display: 'flex', alignItems: 'center', gap: '1', listStyle: 'none' },
    trigger: {
      display: 'flex',
      alignItems: 'center',
      gap: '1.5',
      h: '9',
      px: '3',
      borderRadius: 'l2',
      textStyle: 'sm',
      fontWeight: 'medium',
      color: 'fg.muted',
      cursor: 'pointer',
      outline: '0',
      transitionProperty: 'background-color, color',
      transitionDuration: 'fast',
      focusVisibleRing: 'outside',
      _hover: { bg: 'gray.plain.bg.hover', color: 'fg.default' },
      _open: { bg: 'gray.plain.bg.hover', color: 'fg.default' },
    },
    icon: {
      display: 'flex',
      transitionProperty: 'rotate',
      transitionDuration: 'normal',
      _icon: { boxSize: '3.5' },
      _open: { rotate: '180deg' },
    },
    positioner: { zIndex: 'popover' },
    popup: {
      ...popup,
      boxShadow: 'lg',
      maxWidth: 'min(token(sizes.lg), calc(100vw - token(spacing.6)))',
    },
    viewport: { position: 'relative', overflow: 'hidden' },
    content: { p: '2' },
    link: {
      display: 'block',
      px: '3',
      py: '2.5',
      borderRadius: 'l2',
      textStyle: 'sm',
      color: 'fg.default',
      textDecoration: 'none',
      outline: '0',
      focusVisibleRing: 'inside',
      _hover: { bg: 'gray.surface.bg.hover' },
      '&[data-active]': { color: 'colorPalette.plain.fg' },
    },
  },
})
