import { defineSlotRecipe } from '@pandacss/dev'
import { focusRing } from '../shared'
export const toast = defineSlotRecipe({
  className: 'kiso-toast',
  slots: ['viewport', 'root', 'content', 'title', 'description', 'close', 'action'],
  staticCss: ['*'],
  base: {
    viewport: {
      position: 'fixed',
      bottom: '5',
      insetInlineEnd: '5',
      zIndex: 'toast',
      width: '340px',
      maxWidth: 'calc(100vw - 40px)',
      display: 'flex',
      flexDirection: 'column',
      gap: '3',
      outline: 'none',
    },
    root: {
      position: 'relative',
      bg: 'surface.raised',
      color: 'fg',
      border: '1px solid',
      borderColor: 'border',
      borderRadius: 'l3',
      boxShadow: 'lg',
      p: '4',
      transition: 'opacity 180ms, transform 180ms',
      transform:
        'translateX(var(--toast-swipe-movement-x, 0px)) translateY(var(--toast-swipe-movement-y, 0px))',
      _startingStyle: { opacity: 0, transform: 'translateY(12px)' },
      _endingStyle: { opacity: 0, transform: 'translateX(24px)' },
      '&[data-limited]': { display: 'none' },
      '&[data-type=success]': { borderColor: 'success' },
      '&[data-type=error]': { borderColor: 'danger' },
    },
    content: { paddingInlineEnd: '6' },
    title: { fontSize: 'sm', fontWeight: 'medium' },
    description: { mt: '1', fontSize: 'xs', color: 'fg.muted', lineHeight: '1.6' },
    close: {
      ...focusRing,
      position: 'absolute',
      top: '3',
      insetInlineEnd: '3',
      w: '5',
      h: '5',
      display: 'grid',
      placeItems: 'center',
      color: 'fg.muted',
      borderRadius: 'l1',
      _hover: { bg: 'surface.hover' },
    },
    action: {
      ...focusRing,
      fontSize: 'xs',
      color: 'accent.fg',
      fontWeight: 'medium',
      mt: '3',
      borderRadius: '3px',
    },
  },
})
