import { defineSlotRecipe } from '@pandacss/dev'

// Base UI sets data-type from toast.add({ type }); success / error / warning / info pick a palette.
export const toast = defineSlotRecipe({
  className: 'kiso-toast',
  jsx: ['Toast', /^Toast\./, 'Toaster'],
  slots: ['viewport', 'root', 'content', 'title', 'description', 'close', 'action'],
  staticCss: ['*'],
  base: {
    viewport: {
      position: 'fixed',
      bottom: '4',
      insetInlineEnd: '4',
      zIndex: 'toast',
      display: 'flex',
      flexDirection: 'column',
      gap: '3',
      width: 'sm',
      maxWidth: 'calc(100vw - token(spacing.8))',
      outline: '0',
    },
    root: {
      position: 'relative',
      display: 'flex',
      alignItems: 'flex-start',
      gap: '3',
      p: '4',
      bg: 'gray.surface.bg',
      color: 'fg.default',
      borderRadius: 'l3',
      boxShadow: 'lg',
      textStyle: 'sm',
      transitionProperty: 'opacity, translate',
      transitionDuration: 'normal',
      translate: 'var(--toast-swipe-movement-x, 0px) var(--toast-swipe-movement-y, 0px)',
      _startingStyle: { opacity: 0, translate: '0 token(spacing.3)' },
      _endingStyle: { opacity: 0, translate: 'token(spacing.6) 0' },
      '&[data-limited]': { display: 'none' },
      // A palette accent on the leading edge marks the type.
      '&[data-type=success]': { colorPalette: 'success' },
      '&[data-type=error]': { colorPalette: 'danger' },
      '&[data-type=warning]': { colorPalette: 'warning' },
      '&[data-type=info]': { colorPalette: 'info' },
      '&[data-type]': {
        borderInlineStartWidth: '3px',
        borderInlineStartColor: 'colorPalette.solid.bg',
      },
    },
    content: { display: 'flex', flexDirection: 'column', gap: '1', flex: '1', minWidth: '0' },
    title: { fontWeight: 'semibold' },
    description: { color: 'fg.muted' },
    close: {
      display: 'grid',
      placeItems: 'center',
      flexShrink: '0',
      boxSize: '6',
      mt: '-1',
      mr: '-1',
      color: 'fg.subtle',
      borderRadius: 'l2',
      cursor: 'pointer',
      focusVisibleRing: 'outside',
      _hover: { bg: 'gray.plain.bg.hover', color: 'fg.default' },
      _icon: { boxSize: '4' },
    },
    action: {
      alignSelf: 'center',
      flexShrink: '0',
      h: '8',
      px: '3',
      borderRadius: 'l2',
      fontWeight: 'semibold',
      textStyle: 'sm',
      bg: 'colorPalette.subtle.bg',
      color: 'colorPalette.subtle.fg',
      cursor: 'pointer',
      focusVisibleRing: 'outside',
      _hover: { bg: 'colorPalette.subtle.bg.hover' },
    },
  },
})
