export type Category = 'Actions' | 'Forms' | 'Feedback' | 'Navigation' | 'Overlays' | 'Layout'
export interface ComponentEntry {
  id: string
  name: string
  category: Category
  description: string
  recipe?: string
  base?: string
  variants?: string[]
  sizes?: string[]
  palettes?: string[]
  anatomy: string[]
  note: string
}
export const catalog: ComponentEntry[] = [
  {
    id: 'table',
    name: 'Table',
    category: 'Layout',
    description: 'A clear view of the details that matter.',
    recipe: 'table',
    sizes: ['sm', 'md', 'lg'],
    variants: ['line', 'striped'],
    anatomy: ['Container', 'Root', 'Header', 'Body', 'Footer', 'Row', 'Head', 'Cell', 'Caption'],
    note: 'Native table semantics with column headers by default. Use Container for horizontal overflow with keyboard access; give it a specific aria-label when there are several tables. Sorting and filtering belong in your data layer; no table engine is bundled.',
  },
  {
    id: 'breadcrumb',
    recipe: 'breadcrumb',
    name: 'Breadcrumb',
    category: 'Navigation',
    description: 'A little context for where you are.',
    anatomy: ['Root', 'List', 'Item', 'Link', 'Current', 'Separator'],
    note: 'Use links for parent pages and Current for the current page. Separators are decorative and hidden from assistive technology.',
  },
  {
    id: 'pagination',
    recipe: 'pagination',
    name: 'Pagination',
    category: 'Navigation',
    description: 'A steady path through a longer collection.',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Pagination'],
    note: 'count is the total number of pages. Supports page/onPageChange or defaultPage. Navigation clamps within the page count; changes from external count updates are not emitted as user events.',
  },
  {
    id: 'spinner',
    recipe: 'spinner',
    name: 'Spinner',
    category: 'Feedback',
    description: 'A small sign that something is happening.',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Spinner'],
    note: 'Announces the label through a status region. Use aria-hidden on decorative spinners inside an already labeled busy button. Honors the foundation’s reduced-motion rules.',
  },
  {
    id: 'empty-state',
    name: 'Empty State',
    category: 'Feedback',
    description: 'An open canvas should feel like an invitation.',
    recipe: 'empty-state',
    sizes: ['sm', 'md', 'lg'],
    variants: ['outline', 'plain'],
    anatomy: ['Root', 'Icon', 'Title', 'Description', 'Actions'],
    note: 'Explain why the region is empty and offer one useful next step. An empty state is ordinary content; it should not announce repeatedly through a live region.',
  },
  {
    id: 'button-group',
    recipe: 'button-group',
    name: 'Button Group',
    category: 'Actions',
    description: 'Related actions, with a shared rhythm.',
    anatomy: ['ButtonGroup'],
    note: 'Supports horizontal/vertical orientation and attached styling. Provide an accessible group label. For arrow-key navigation, use Toolbar instead.',
  },
  {
    id: 'combobox',
    name: 'Combobox',
    category: 'Forms',
    description: 'Find the right option, one keystroke at a time.',
    recipe: 'combobox',
    base: 'combobox',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: [
      'Root',
      'InputGroup',
      'Input',
      'Trigger',
      'Clear',
      'Portal',
      'Positioner',
      'Popup',
      'List',
      'Item',
      'ItemIndicator',
      'Empty',
      'Chips',
      'Chip',
      'ChipRemove',
    ],
    note: 'Supports single and multiple values with generic type inference. Keep the input visibly labeled. Chips are available for multiple selection; list callbacks receive each filtered item.',
  },
  {
    id: 'autocomplete',
    name: 'Autocomplete',
    category: 'Forms',
    description: 'A helpful suggestion, with room for your own words.',
    recipe: 'combobox',
    base: 'autocomplete',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: [
      'Root',
      'InputGroup',
      'Input',
      'Portal',
      'Positioner',
      'Popup',
      'List',
      'Item',
      'Empty',
    ],
    note: 'Use for free-form text with suggestions. Unlike Combobox, the value can be something outside the list. Object items need itemToStringValue.',
  },
  {
    id: 'checkbox-group',
    recipe: 'checkbox-group',
    name: 'Checkbox Group',
    category: 'Forms',
    description: 'A few independent choices, held together.',
    base: 'checkbox-group',
    anatomy: ['CheckboxGroup'],
    note: 'Compose with Checkbox.Root using a value on each checkbox. The group supports controlled values and parent-child selection. Give the group a visible label or aria-label.',
  },
  {
    id: 'fieldset',
    name: 'Fieldset',
    category: 'Forms',
    description: 'Related fields, with a shared purpose.',
    recipe: 'fieldset',
    base: 'fieldset',
    variants: ['plain', 'card'],
    anatomy: ['Root', 'Legend'],
    note: 'A semantic fieldset and legend. Compose with Field for individually labeled inputs and descriptions.',
  },
  {
    id: 'form',
    recipe: 'form',
    name: 'Form',
    category: 'Forms',
    description: 'A complete form, from first input to clear feedback.',
    base: 'form',
    anatomy: ['Form'],
    note: 'Base UI Form integrates field validation and server errors. Its onFormSubmit callback receives form values after validation. Layout is a simple vertical stack.',
  },
  {
    id: 'otp-field',
    name: 'OTP Field',
    category: 'Forms',
    description: 'A short code, with all the small details handled.',
    recipe: 'otp-field',
    base: 'otp-field',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Root', 'Input', 'Separator'],
    note: 'Set length on Root and render that many Inputs. Supports pasting, backspace, keyboard navigation and one-time-code autofill. Label each slot clearly.',
  },
  {
    id: 'toast',
    name: 'Toast',
    category: 'Feedback',
    description: 'A little reassurance, without an interruption.',
    recipe: 'toast',
    base: 'toast',
    anatomy: [
      'Provider',
      'Toaster',
      'Root',
      'Viewport',
      'Content',
      'Title',
      'Description',
      'Action',
      'Close',
    ],
    note: 'Mount Toaster once inside Provider. useToastManager supports add, update, close and promise. Toast announcements and timeout pausing are handled by Base UI.',
  },
  {
    id: 'meter',
    name: 'Meter',
    category: 'Feedback',
    description: 'A measurement with a little perspective.',
    recipe: 'progress',
    base: 'meter',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
    anatomy: ['Root', 'Label', 'Value', 'Track', 'Indicator'],
    note: 'Use Meter for a measurement within a known range, such as capacity. Use Progress for the completion of a task. Always include a label.',
  },
  {
    id: 'collapsible',
    name: 'Collapsible',
    category: 'Navigation',
    description: 'Keep extra details close, without the clutter.',
    recipe: 'collapsible',
    base: 'collapsible',
    anatomy: ['Root', 'Trigger', 'Panel'],
    note: 'A single expandable region. Put panel content in a div so its padding works with the height animation.',
  },
  {
    id: 'navigation-menu',
    name: 'Navigation Menu',
    category: 'Navigation',
    description: 'A thoughtful way into the rest of your product.',
    recipe: 'navigation-menu',
    base: 'navigation-menu',
    anatomy: [
      'Root',
      'List',
      'Item',
      'Trigger',
      'Content',
      'Portal',
      'Positioner',
      'Popup',
      'Viewport',
      'Link',
    ],
    note: 'Use real links for navigation. The popup viewport hosts the active content. Keep the navigation labeled and support both pointer and keyboard exploration.',
  },
  {
    id: 'menubar',
    recipe: 'menubar',
    name: 'Menubar',
    category: 'Navigation',
    description: 'Familiar menus for an application workspace.',
    base: 'menubar',
    anatomy: ['Menubar'],
    note: 'Compose with Menu roots and triggers. Keyboard arrow navigation between menus is managed by Base UI. This is for application commands, not site navigation.',
  },
  {
    id: 'toolbar',
    name: 'Toolbar',
    category: 'Actions',
    description: 'The tools you need, together in one place.',
    recipe: 'toolbar',
    base: 'toolbar',
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Group', 'Button', 'Link', 'Input', 'Separator'],
    note: 'A single tab stop with arrow-key navigation. Use render to compose Toolbar.Button with Toggle for formatting controls.',
  },
  {
    id: 'context-menu',
    name: 'Context Menu',
    category: 'Overlays',
    description: 'Relevant actions, right where you are.',
    recipe: 'menu',
    base: 'context-menu',
    sizes: ['sm', 'md'],
    anatomy: ['Root', 'Trigger', 'Portal', 'Positioner', 'Popup', 'Item', 'Separator'],
    note: 'Opens on a context menu gesture. Ensure the trigger is keyboard focusable and that essential actions are also discoverable elsewhere.',
  },
  {
    id: 'drawer',
    name: 'Drawer',
    category: 'Overlays',
    description: 'A focused panel that meets you where you are.',
    recipe: 'drawer',
    base: 'drawer',
    sizes: ['sm', 'md', 'lg'],
    anatomy: [
      'Root',
      'Trigger',
      'Portal',
      'Backdrop',
      'Viewport',
      'Popup',
      'Content',
      'Title',
      'Description',
      'Close',
    ],
    note: 'The recipe targets a bottom drawer with swipeDirection="down". Includes focus trapping, dismissal and reduced-motion support. Use Dialog for a centered modal.',
  },
  {
    id: 'preview-card',
    name: 'Preview Card',
    category: 'Overlays',
    description: 'A glimpse of what is on the other side.',
    recipe: 'popover',
    base: 'preview-card',
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Trigger', 'Portal', 'Positioner', 'Popup', 'Arrow'],
    note: 'Supplement a meaningful link with a preview. Keep essential information outside the hover card because touch users may follow the link directly.',
  },
  {
    id: 'scroll-area',
    name: 'Scroll Area',
    category: 'Layout',
    description: 'More content, with a little less visual noise.',
    recipe: 'scroll-area',
    base: 'scroll-area',
    anatomy: ['Root', 'Viewport', 'Content', 'Scrollbar', 'Thumb', 'Corner'],
    note: 'Give Root a constrained size. Viewport supports keyboard scrolling; scrollbars appear on hover or scrolling. Horizontal scrollbars use orientation="horizontal".',
  },
  {
    id: 'button',
    palettes: ['accent', 'neutral', 'danger', 'success'],
    name: 'Button',
    category: 'Actions',
    description: 'A clear next step, in every shape and state.',
    recipe: 'button',
    base: 'button',
    variants: ['solid', 'subtle', 'surface', 'outline', 'plain'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Button'],
    note: 'Use nativeButton={false} when composing a link through render. Icon-only buttons need an accessible label. colorPalette is independent of variant; prefer colorPalette="danger" with any variant for destructive actions. The danger variant is a solid shorthand. Size also accepts responsive values such as { base: "sm", md: "lg" }.',
  },
  {
    id: 'toggle',
    name: 'Toggle',
    category: 'Actions',
    description: 'An action that stays on until you turn it off.',
    recipe: 'toggle',
    base: 'toggle',
    variants: ['ghost', 'outline'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Toggle', 'ToggleGroup'],
    note: 'pressed and onPressedChange support controlled state. Use ToggleGroup for a related set of choices.',
  },
  {
    id: 'input',
    name: 'Input',
    category: 'Forms',
    description: 'A quiet, dependable place to start typing.',
    recipe: 'input',
    base: 'input',
    variants: ['outline', 'surface', 'subtle'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Input'],
    note: 'Wrap with Field.Root and Field.Label for automatic label, description and validation associations. size is a visual variant.',
  },
  {
    id: 'textarea',
    name: 'Textarea',
    category: 'Forms',
    description: 'Make room for a longer thought.',
    recipe: 'textarea',
    variants: ['outline', 'surface', 'subtle'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Textarea'],
    note: 'A native textarea with the input recipe. Use Field.Control render={<Textarea />} for Base UI field integration.',
  },
  {
    id: 'field',
    name: 'Field',
    category: 'Forms',
    description: 'Labels, hints, and validation that belong together.',
    recipe: 'field',
    base: 'field',
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Label', 'Description', 'Error', 'Control', 'Validity'],
    note: 'Base UI connects label and description IDs automatically. Error can use match to select a native validity state.',
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    category: 'Forms',
    description: 'One choice, or a few. Always explicit.',
    recipe: 'checkbox',
    base: 'checkbox',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Root', 'Indicator'],
    note: 'Put Root inside a label, or use aria-labelledby. Supports checked, indeterminate, disabled and form submission.',
  },
  {
    id: 'radio-group',
    name: 'Radio Group',
    category: 'Forms',
    description: 'One good choice from a small set.',
    recipe: 'radio-group',
    base: 'radio-group',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Root', 'Item', 'Indicator'],
    note: 'Give the group an accessible name. Arrow keys move between options; individual labels belong to each Item.',
  },
  {
    id: 'switch',
    name: 'Switch',
    category: 'Forms',
    description: 'An immediate change, with an unmistakable state.',
    recipe: 'switch',
    base: 'switch',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Root', 'Thumb'],
    note: 'Use for settings that apply immediately. Name the setting with a label; do not put on/off in the accessible name.',
  },
  {
    id: 'select',
    name: 'Select',
    category: 'Forms',
    description: 'Choose an option without losing your place.',
    recipe: 'select',
    base: 'select',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: [
      'Root',
      'Trigger',
      'Value',
      'Icon',
      'Portal',
      'Positioner',
      'Popup',
      'List',
      'Item',
      'ItemText',
      'ItemIndicator',
    ],
    note: 'Root retains generic value inference and multiple selection. Pass items for stable value labels; use alignItemWithTrigger={false} for a conventional popup.',
  },
  {
    id: 'slider',
    name: 'Slider',
    category: 'Forms',
    description: 'Fine-tune a value with a little more feeling.',
    recipe: 'slider',
    base: 'slider',
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Label', 'Value', 'Control', 'Track', 'Indicator', 'Thumb'],
    note: 'Use Label and a meaningful getAriaValueText for units. For a range, render one Thumb per value. Vertical sliders are supported; adjust the height on Control for your layout.',
  },
  {
    id: 'number-field',
    name: 'Number Field',
    category: 'Forms',
    description: 'Precise numbers, comfortably within bounds.',
    recipe: 'number-field',
    base: 'number-field',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Root', 'Group', 'Input', 'Increment', 'Decrement', 'ScrubArea'],
    note: 'Pass min, max, step and locale to Root. Label the input and both step buttons.',
  },
  {
    id: 'badge',
    name: 'Badge',
    category: 'Feedback',
    description: 'A small amount of context goes a long way.',
    recipe: 'badge',
    variants: ['solid', 'subtle', 'surface', 'outline'],
    sizes: ['sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Badge'],
    note: 'tone selects neutral, accent, success, warning or danger. Status text must communicate meaning without relying on color.',
  },
  {
    id: 'alert',
    name: 'Alert',
    category: 'Feedback',
    description: 'The right message, at the right level of urgency.',
    recipe: 'alert',
    anatomy: ['Root', 'Icon', 'Title', 'Description'],
    note: 'tone selects info, success, warning or danger. Use role="alert" only for urgent dynamic changes; static information needs no live region.',
  },
  {
    id: 'progress',
    name: 'Progress',
    category: 'Feedback',
    description: 'Make a little progress visible.',
    recipe: 'progress',
    base: 'progress',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
    anatomy: ['Root', 'Label', 'Value', 'Track', 'Indicator'],
    note: 'Set value and max on Root. Base UI manages the indicator width and progress semantics. Use null for an indeterminate task.',
  },
  {
    id: 'skeleton',
    recipe: 'skeleton',
    name: 'Skeleton',
    category: 'Feedback',
    description: 'A calm placeholder while the content arrives.',
    anatomy: ['Skeleton'],
    note: 'Decorative skeletons are hidden from assistive technology. Put aria-busy on the loading region and announce loading separately.',
  },
  {
    id: 'tabs',
    name: 'Tabs',
    category: 'Navigation',
    description: 'Related views, with one clear focus.',
    recipe: 'tabs',
    base: 'tabs',
    variants: ['enclosed', 'line'],
    sizes: ['xs', 'sm', 'md', 'lg'],
    anatomy: ['Root', 'List', 'Tab', 'Panel', 'Indicator'],
    note: 'List needs an accessible label. Use matching value props on Tab and Panel. Horizontal and vertical orientations are supported. Keyboard behavior and activation mode come from Base UI.',
  },
  {
    id: 'accordion',
    name: 'Accordion',
    category: 'Navigation',
    description: 'Let the details unfold at their own pace.',
    recipe: 'accordion',
    base: 'accordion',
    variants: ['line', 'enclosed'],
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Item', 'Header', 'Trigger', 'Panel'],
    note: 'Put Trigger inside Header. Put panel content in a div for padding that does not break height animations. Multiple panels can be open.',
  },
  {
    id: 'dialog',
    name: 'Dialog',
    category: 'Overlays',
    description: 'A focused space for an important next step.',
    recipe: 'dialog',
    base: 'dialog',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
    anatomy: ['Root', 'Trigger', 'Portal', 'Backdrop', 'Popup', 'Title', 'Description', 'Close'],
    note: 'Always include a Title. Base UI handles focus trapping, dismissal and focus return. Portal keeps the popup outside page stacking contexts.',
  },
  {
    id: 'alert-dialog',
    name: 'Alert Dialog',
    category: 'Overlays',
    description: 'A moment to confirm before moving forward.',
    recipe: 'dialog',
    base: 'alert-dialog',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
    anatomy: ['Root', 'Trigger', 'Portal', 'Backdrop', 'Popup', 'Title', 'Description', 'Close'],
    note: 'Reserve for decisions that need a response. Provide a safe cancel action and a clearly named confirmation.',
  },
  {
    id: 'popover',
    name: 'Popover',
    category: 'Overlays',
    description: 'A little more context, just within reach.',
    recipe: 'popover',
    base: 'popover',
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Trigger', 'Portal', 'Positioner', 'Popup', 'Title', 'Description', 'Close'],
    note: 'Use sideOffset on Positioner for spacing. Root owns open state and style variants; context survives the portal.',
  },
  {
    id: 'menu',
    name: 'Menu',
    category: 'Overlays',
    description: 'Useful actions, neatly tucked away.',
    recipe: 'menu',
    base: 'menu',
    sizes: ['sm', 'md'],
    anatomy: [
      'Root',
      'Trigger',
      'Portal',
      'Positioner',
      'Popup',
      'Item',
      'Group',
      'GroupLabel',
      'Separator',
      'SubmenuRoot',
    ],
    note: 'Use menus for actions. Use Select for a form value. Disabled and highlighted states are provided by Base UI.',
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    category: 'Overlays',
    description: 'A helpful hint that never gets in the way.',
    recipe: 'tooltip',
    base: 'tooltip',
    anatomy: ['Provider', 'Root', 'Trigger', 'Portal', 'Positioner', 'Popup'],
    note: 'Wrap related tooltips in Provider. A tooltip supplements an accessible label; it must not be the only label for a control.',
  },
  {
    id: 'avatar',
    name: 'Avatar',
    category: 'Layout',
    description: 'A familiar face. A thoughtful fallback.',
    recipe: 'avatar',
    base: 'avatar',
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    anatomy: ['Root', 'Image', 'Fallback'],
    note: 'Image needs alt text. Give the root an accessible name when displaying initials alone. shape supports circle and square.',
  },
  {
    id: 'card',
    name: 'Card',
    category: 'Layout',
    description: 'A place for things that belong together.',
    recipe: 'card',
    variants: ['outline', 'elevated', 'subtle'],
    sizes: ['sm', 'md', 'lg'],
    anatomy: ['Root', 'Header', 'Title', 'Description', 'Body', 'Footer'],
    note: 'A structural component with no invented interaction. Use a real button or link inside the card for actions.',
  },
  {
    id: 'separator',
    recipe: 'separator',
    name: 'Separator',
    category: 'Layout',
    description: 'A small pause between related ideas.',
    base: 'separator',
    anatomy: ['Separator'],
    note: 'Supports horizontal and vertical orientation. For decoration only, set aria-hidden.',
  },
  {
    id: 'kbd',
    recipe: 'kbd',
    name: 'Kbd',
    category: 'Layout',
    description: 'Make a keyboard shortcut easy to discover.',
    anatomy: ['Kbd'],
    note: 'Uses the native kbd element. Showing a shortcut does not register a keyboard handler.',
  },
]
export const categories: Category[] = [
  'Actions',
  'Forms',
  'Feedback',
  'Navigation',
  'Overlays',
  'Layout',
]
catalog.sort((a, b) => a.name.localeCompare(b.name))
