export const nativeExamples: Record<string, string> = {
  table: `import * as Table from './components/ui/table'\n\n<Table.Container>\n  <Table.Root size="md" variant="plain" interactive>\n    <Table.Caption>Projects in your workspace.</Table.Caption>\n    <Table.Header><Table.Row><Table.Head>Project</Table.Head><Table.Head>Status</Table.Head></Table.Row></Table.Header>\n    <Table.Body><Table.Row><Table.Cell>Studio North</Table.Cell><Table.Cell>Published</Table.Cell></Table.Row></Table.Body>\n  </Table.Root>\n</Table.Container>`,
  breadcrumb: `import * as Breadcrumb from './components/ui/breadcrumb'\n\n<Breadcrumb.Root>\n  <Breadcrumb.List>\n    <Breadcrumb.Item><Breadcrumb.Link href="/">Home</Breadcrumb.Link></Breadcrumb.Item>\n    <Breadcrumb.Separator />\n    <Breadcrumb.Item><Breadcrumb.Current>Components</Breadcrumb.Current></Breadcrumb.Item>\n  </Breadcrumb.List>\n</Breadcrumb.Root>`,
  pagination: `import { useState } from 'react'\nimport { Pagination } from './components/ui/pagination'\n\nexport function Example() {\n  const [page, setPage] = useState(1)\n  return <Pagination count={12} page={page} onPageChange={setPage} />\n}`,
  spinner: `import { Spinner } from './components/ui/spinner'\n\n<Spinner size="md" label="Loading projects" />`,
  'empty-state': `import * as EmptyState from './components/ui/empty-state'\nimport { Button } from './components/ui/button'\n\n<EmptyState.Root>\n  <EmptyState.Title>Every good thing starts somewhere.</EmptyState.Title>\n  <EmptyState.Description>Make room for your next big idea.</EmptyState.Description>\n  <EmptyState.Actions><Button>Create a project</Button></EmptyState.Actions>\n</EmptyState.Root>`,
  'button-group': `import { ButtonGroup } from './components/ui/button-group'\nimport { Button } from './components/ui/button'\n\n<ButtonGroup attached aria-label="Browse pages">\n  <Button variant="outline">Previous</Button>\n  <Button variant="outline">Next</Button>\n</ButtonGroup>`,
  'input-group': `import { useRef, useState } from 'react'\nimport * as InputGroup from './components/ui/input-group'\nimport { Input } from './components/ui/input'\nimport { Button } from './components/ui/button'\n\nexport function Example() {\n  const [query, setQuery] = useState('')\n  const input = useRef<HTMLInputElement>(null)\n  return <>\n    <InputGroup.Root>\n      <InputGroup.Element>\n        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="11" cy="11" r="7" /><path d="m20 20-3.5-3.5" /></svg>\n      </InputGroup.Element>\n      <Input ref={input} type="search" aria-label="Search projects" placeholder="Search projects" value={query} onChange={(event) => setQuery(event.target.value)} />\n      {query && (\n        <InputGroup.Element>\n          <Button variant="plain" colorPalette="gray" size="xs" square aria-label="Clear search" onClick={() => { setQuery(''); input.current?.focus() }}>\n            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M18 6 6 18M6 6l12 12" /></svg>\n          </Button>\n        </InputGroup.Element>\n      )}\n    </InputGroup.Root>\n    <InputGroup.Root>\n      <InputGroup.Addon>https://</InputGroup.Addon>\n      <Input aria-label="Website" placeholder="studio-north" />\n      <InputGroup.Addon>.com</InputGroup.Addon>\n    </InputGroup.Root>\n  </>\n}`,
}
