export const accentNames = [
  'amber',
  'blue',
  'bronze',
  'brown',
  'crimson',
  'cyan',
  'gold',
  'grass',
  'green',
  'indigo',
  'iris',
  'jade',
  'lime',
  'mauve',
  'mint',
  'neutral',
  'olive',
  'orange',
  'pink',
  'plum',
  'purple',
  'red',
  'ruby',
  'sage',
  'sand',
  'sky',
  'slate',
  'teal',
  'tomato',
  'violet',
  'yellow',
] as const
export const grayNames = ['neutral', 'mauve', 'olive', 'sage', 'sand', 'slate'] as const
export const radiusNames = ['none', 'xs', 'sm', 'md', 'lg', 'xl', '2xl'] as const
export const radiusLevels: Record<string, readonly [number, number, number]> = {
  none: [0, 0, 0],
  xs: [0, 2, 4],
  sm: [2, 4, 6],
  md: [4, 6, 8],
  lg: [6, 8, 12],
  xl: [8, 12, 16],
  '2xl': [12, 16, 24],
}
