import { css } from '../../styled-system/css'

export const styles = {
  layout: css({
    display: 'grid',
    gridTemplateColumns: { base: '1fr', lg: '224px 1fr' },
    minHeight: '100dvh',
  }),
  sidebar: css({
    display: { base: 'none', lg: 'flex' },
    flexDirection: 'column',
    borderInlineEndWidth: '1px',
    borderInlineEndStyle: 'solid',
    borderColor: 'border',
    bg: 'canvas',
    position: 'fixed',
    insetBlock: 0,
    insetInlineStart: 0,
    width: '224px',
    zIndex: 'docked',
  }),
  brand: css({
    display: 'flex',
    alignItems: 'center',
    gap: '2.5',
    fontSize: '22px',
    letterSpacing: '-.07em',
    fontWeight: 'semibold',
    color: 'fg.default',
    textDecoration: 'none',
  }),
  brandMark: css({
    display: 'grid',
    placeItems: 'center',
    w: '7',
    h: '7',
    borderRadius: '7px',
    bg: 'fg.default',
    color: 'gray.1',
    fontSize: '25px',
    fontWeight: 'normal',
    lineHeight: 1,
    letterSpacing: 0,
  }),
  sidebarTop: css({ px: '6', pt: '7', pb: '6' }),
  sidebarNav: css({ px: '3', overflowY: 'auto', flex: 1, pb: '6', scrollbarWidth: 'thin' }),
  navLabel: css({
    px: '3',
    mt: '6',
    mb: '2',
    fontSize: '10px',
    fontWeight: 'medium',
    letterSpacing: '.08em',
    color: 'fg.muted',
    textTransform: 'uppercase',
  }),
  navLink: css({
    display: 'flex',
    alignItems: 'center',
    gap: '2.5',
    w: 'full',
    px: '3',
    py: '1.5',
    my: '0.5',
    borderRadius: 'l2',
    color: 'fg.muted',
    fontSize: '12px',
    textAlign: 'start',
    textDecoration: 'none',
    transition: 'background 120ms',
    _hover: { bg: 'gray.a4', color: 'fg.default' },
    '&[aria-current=page]': { bg: 'gray.a4', color: 'fg.default', fontWeight: 'medium' },
    '& svg': { w: '3.5', h: '3.5' },
    _focusVisible: {
      outline: '2px solid',
      outlineColor: 'colorPalette.solid.bg',
      outlineOffset: '1px',
    },
  }),
  sidebarFoot: css({
    p: '5',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderColor: 'border',
    display: 'flex',
    alignItems: 'center',
    gap: '2.5',
    fontSize: '11px',
    color: 'fg.muted',
  }),
  content: css({ minWidth: 0, gridColumn: { lg: 2 } }),
  topbar: css({
    height: '72px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderColor: 'border',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: { base: '4', md: '8', xl: '12' },
    gap: '2',
    bg: 'canvas',
  }),
  breadcrumb: css({
    display: { base: 'none', sm: 'flex' },
    alignItems: 'center',
    gap: '2',
    color: 'fg.muted',
    fontSize: '12px',
    '& svg': { w: '3', h: '3', color: 'fg.muted' },
  }),
  topActions: css({ display: 'flex', gap: '2', alignItems: 'center' }),
  search: css({
    display: 'flex',
    alignItems: 'center',
    gap: '2',
    px: '2.5',
    h: '8',
    w: 'full',
    border: '1px solid',
    borderColor: 'border',
    bg: 'gray.surface.bg',
    borderRadius: 'l2',
    color: 'fg.muted',
    fontSize: '11px',
    textAlign: 'start',
    mt: '6',
    _hover: { borderColor: 'gray.outline.border' },
    '& svg': { w: '3.5', h: '3.5' },
  }),
  main: css({
    maxWidth: '1450px',
    mx: 'auto',
    px: { base: '5', md: '8', xl: '12' },
    pt: { base: '8', md: '10' },
    pb: '12',
  }),
  eyebrow: css({
    display: 'flex',
    alignItems: 'center',
    gap: '2',
    color: 'fg.muted',
    fontSize: '11px',
    mb: '4',
    '& span': { width: '1.5', height: '1.5', borderRadius: 'full', bg: 'success.solid.bg' },
  }),
  hero: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8',
    pb: '9',
    '& > div': { minWidth: 0 },
  }),
  heroTitle: css({
    fontSize: { base: '30px', sm: '34px', md: '46px', xl: '50px' },
    lineHeight: '1.1',
    letterSpacing: '-.065em',
    fontWeight: 'medium',
    mb: '4',
    maxWidth: '680px',
  }),
  heroDescription: css({
    fontSize: '14px',
    lineHeight: '1.8',
    color: 'fg.muted',
    maxWidth: '530px',
  }),
  heroArt: css({
    display: { base: 'none', xl: 'block' },
    position: 'relative',
    width: '155px',
    height: '150px',
    flexShrink: 0,
    mr: '7',
  }),
  heroTile: css({
    position: 'absolute',
    w: '100px',
    h: '100px',
    border: '1px solid',
    borderColor: 'gray.outline.border',
    borderRadius: '18px',
    bg: 'gray.surface.bg',
    display: 'grid',
    placeItems: 'center',
    fontSize: '60px',
    color: 'colorPalette.solid.bg',
    boxShadow: 'xs',
  }),
  row: css({ display: 'flex', alignItems: 'center', gap: '2', flexWrap: 'wrap' }),
  spread: css({ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '3' }),
  stack: css({ display: 'flex', flexDirection: 'column', gap: '4' }),
  small: css({ fontSize: 'xs', color: 'fg.muted', lineHeight: '1.6' }),
  title: css({ fontWeight: 'medium', fontSize: 'sm', letterSpacing: '-.015em' }),
  sectionBar: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '3',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderColor: 'border',
    py: '3',
    mb: '6',
  }),
  sectionTabs: css({
    display: 'flex',
    gap: { base: '3', sm: '5' },
    fontSize: '12px',
    color: 'fg.muted',
    '& a': { textDecoration: 'none', py: '1' },
    '& a[aria-current=page]': { color: 'fg.default', fontWeight: 'medium' },
  }),
  gallery: css({
    display: 'grid',
    gridTemplateColumns: {
      base: '1fr',
      md: 'repeat(2,minmax(0,1fr))',
      xl: 'repeat(3,minmax(0,1fr))',
    },
    gap: '5',
    alignItems: 'start',
  }),
  column: css({ display: 'flex', flexDirection: 'column', gap: '5', minWidth: 0 }),
  specimen: css({
    border: '1px solid',
    borderColor: 'border',
    borderRadius: 'l3',
    bg: 'gray.surface.bg',
    overflow: 'hidden',
    boxShadow: 'xs',
  }),
  specimenBody: css({ p: { base: '5', '2xl': '6' } }),
  specimenFoot: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '3',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderColor: 'border',
    bg: 'canvas',
    px: '4',
    py: '2.5',
    fontSize: '10px',
    color: 'fg.muted',
    '& a': {
      display: 'inline-flex',
      gap: '1.5',
      alignItems: 'center',
      color: 'fg.muted',
      textDecoration: 'none',
      _hover: { color: 'colorPalette.solid.bg' },
    },
    '& svg': { w: '3', h: '3' },
  }),
  notification: css({
    display: 'flex',
    gap: '4',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: '3',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderColor: 'border',
    _last: { borderBottom: 0, pb: 0 },
  }),
  glyph: css({
    w: '9',
    h: '9',
    border: '1px solid',
    borderColor: 'border',
    borderRadius: 'l2',
    display: 'grid',
    placeItems: 'center',
    color: 'fg.muted',
    bg: 'canvas',
    '& svg': { w: '4', h: '4' },
  }),
  metric: css({ fontSize: '30px', fontWeight: 'medium', letterSpacing: '-.06em', lineHeight: 1.2 }),
  bars: css({
    display: 'flex',
    gap: '4px',
    height: '70px',
    alignItems: 'end',
    mt: '5',
    '& span': {
      flex: 1,
      borderRadius: '2px 2px 0 0',
      bg: 'colorPalette.subtle.bg',
      _last: { bg: 'colorPalette.solid.bg' },
    },
  }),
  footer: css({
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: '3',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderColor: 'border',
    mt: '9',
    pt: '5',
    fontSize: '11px',
    color: 'fg.muted',
  }),
  pageTitle: css({
    fontSize: { base: '32px', md: '40px' },
    fontWeight: 'medium',
    letterSpacing: '-.055em',
    lineHeight: '1.2',
    mb: '3',
  }),
  pageIntro: css({
    color: 'fg.muted',
    fontSize: '15px',
    lineHeight: '1.7',
    maxWidth: '650px',
    mb: '7',
  }),
  detailGrid: css({
    display: 'grid',
    gridTemplateColumns: { base: '1fr', xl: 'minmax(0,1fr) 230px' },
    gap: '7',
    mt: '7',
  }),
  preview: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '280px',
    p: { base: '5', md: '10' },
    backgroundImage: 'radial-gradient(token(colors.border) .7px, transparent .7px)',
    backgroundSize: '12px 12px',
    bg: 'canvas',
    borderRadius: 'l3',
    border: '1px solid',
    borderColor: 'border',
  }),
  code: css({
    border: '1px solid',
    borderColor: 'border',
    borderRadius: 'l3',
    bg: 'gray.surface.bg',
    overflow: 'hidden',
  }),
  codeHead: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '3',
    px: '4',
    py: '2',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderColor: 'border',
    fontSize: '11px',
    color: 'fg.muted',
  }),
  pre: css({
    p: '5',
    overflow: 'auto',
    maxHeight: '480px',
    fontSize: '12px',
    fontFamily: 'mono',
    lineHeight: '1.9',
    color: 'fg.muted',
    tabSize: 2,
  }),
  docHeading: css({
    fontSize: '19px',
    fontWeight: 'medium',
    letterSpacing: '-.035em',
    mt: '9',
    mb: '4',
  }),
  prose: css({
    color: 'fg.muted',
    fontSize: 'sm',
    lineHeight: '1.85',
    maxWidth: '760px',
    '& a': {
      color: 'colorPalette.plain.fg',
      textDecoration: 'underline',
      textUnderlineOffset: '3px',
    },
    '& code': {
      fontFamily: 'mono',
      fontSize: '.9em',
      bg: 'gray.subtle.bg',
      px: '1',
      borderRadius: '3px',
    },
    '& p + p': { mt: '3' },
  }),
  table: css({
    width: 'full',
    textAlign: 'start',
    fontSize: 'xs',
    borderCollapse: 'collapse',
    '& th': {
      color: 'fg.muted',
      fontWeight: 'normal',
      py: '3',
      borderBottomWidth: '1px',
      borderBottomStyle: 'solid',
      borderColor: 'border',
      textAlign: 'start',
    },
    '& td': {
      py: '3',
      borderBottomWidth: '1px',
      borderBottomStyle: 'solid',
      borderColor: 'border',
      color: 'fg.muted',
      pr: '3',
      verticalAlign: 'top',
    },
    '& code': { fontFamily: 'mono', fontSize: '11px', color: 'colorPalette.plain.fg' },
  }),
  componentGrid: css({
    display: 'grid',
    gridTemplateColumns: { base: '1fr', md: 'repeat(2,1fr)', xl: 'repeat(3,1fr)' },
    gap: '4',
  }),
  catalogCard: css({
    display: 'block',
    p: '5',
    border: '1px solid',
    borderColor: 'border',
    borderRadius: 'l3',
    bg: 'gray.surface.bg',
    textDecoration: 'none',
    transition: 'border-color 150ms, transform 150ms',
    _hover: { borderColor: 'colorPalette.solid.bg', transform: 'translateY(-2px)' },
    _focusVisible: { outline: '2px solid', outlineColor: 'colorPalette.solid.bg' },
  }),
  empty: css({ py: '16', textAlign: 'center', color: 'fg.muted' }),
  mobileNav: css({ display: { base: 'block', lg: 'none' }, maxWidth: '140px', minWidth: 0 }),
}
